name: Docker Image CI FRONT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Connnect to DockerHub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
            docker login -u $username -p $password 
            
    - name: Build the Docker image
      run: cd front/url-shortener-front && docker build -t aminejava/urlshortener-front .

    - name: print the docker images
      id: print-docker-image
      run: docker images
    - name: push the docker image
      id: push-docker-image
      run: docker push aminejava/urlshortener-front
