name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run maven
      run: mvn clean install
      
    - name: Set up Maven version
      id: get_version
      run: | 
            echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
            echo "Your Project Version is = $PROJECT_VERSION " 
            

    - name: Connnect to DockerHub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
            docker login -u $username -p $password 
            
    - name: Build the Docker image
      run: docker build -t aminejava/urlshortener:${{env.PROJECT_VERSION}}-RC . 

    - name: print the docker images
      id: print-docker-image
      run: docker images
    - name: push the docker image
      id: push-docker-image
      run: docker push aminejava/urlshortener:${{env.PROJECT_VERSION}}-RC
